import { cmd } from "../cmd"
import { UI } from "@/cli/ui"
import { tui } from "./app"
import { win32DisableProcessedInput, win32InstallCtrlCGuard } from "./win32"
import { TuiConfig } from "@/config/tui"
import { Instance } from "@/project/instance"
import { existsSync } from "fs"
import { PairingCode } from "@/pairing/code"

export const AttachCommand = cmd({
  command: "attach [url]",
  describe: "attach to a running codetwin server",
  builder: (yargs) =>
    yargs
      .positional("url", {
        type: "string",
        describe: "http://localhost:4096",
      })
      .option("pair-code", {
        type: "string",
        describe: "pairing code generated by `codetwin pair host`",
      })
      .option("dir", {
        type: "string",
        description: "directory to run in",
      })
      .option("continue", {
        alias: ["c"],
        describe: "continue the last session",
        type: "boolean",
      })
      .option("session", {
        alias: ["s"],
        type: "string",
        describe: "session id to continue",
      })
      .option("fork", {
        type: "boolean",
        describe: "fork the session when continuing (use with --continue or --session)",
      })
      .option("password", {
        alias: ["p"],
        type: "string",
        describe: "basic auth password (defaults to CODETWIN_SERVER_PASSWORD)",
      }),
  handler: async (args) => {
    const unguard = win32InstallCtrlCGuard()
    try {
      win32DisableProcessedInput()

      if (args.fork && !args.continue && !args.session) {
        UI.error("--fork requires --continue or --session")
        process.exitCode = 1
        return
      }

      const pair = (() => {
        if (!args.pairCode) return
        try {
          const decoded = PairingCode.decode(args.pairCode)
          if (PairingCode.isExpired(decoded)) {
            UI.error("pair code has expired")
            process.exitCode = 1
            return null
          }
          return decoded
        } catch (error) {
          const message = error instanceof Error ? error.message : "invalid pair code"
          UI.error(message)
          process.exitCode = 1
          return null
        }
      })()
      if (pair === null) return

      const targetUrl = args.url ?? pair?.url
      if (!targetUrl) {
        UI.error("attach requires <url> or --pair-code")
        process.exitCode = 1
        return
      }

      const directory = (() => {
        if (!args.dir) return undefined
        try {
          process.chdir(args.dir)
          return process.cwd()
        } catch {
          // If the directory doesn't exist locally (remote attach), pass it through.
          return args.dir
        }
      })()
      const headers = (() => {
        const password = args.password ?? pair?.password ?? process.env.CODETWIN_SERVER_PASSWORD
        if (!password) return undefined
        const username = pair?.username ?? process.env.CODETWIN_SERVER_USERNAME ?? "codetwin"
        const auth = `Basic ${Buffer.from(`${username}:${password}`).toString("base64")}`
        return { Authorization: auth }
      })()
      const config = await Instance.provide({
        directory: directory && existsSync(directory) ? directory : process.cwd(),
        fn: () => TuiConfig.get(),
      })
      await tui({
        url: targetUrl,
        config,
        args: {
          continue: args.continue,
          sessionID: args.session,
          fork: args.fork,
        },
        directory,
        headers,
      })
    } finally {
      unguard?.()
    }
  },
})
